### ISSUE TITLE
Firefox extension on linux not showing classification with "loading error"

### ISSUE THREAD

**Issue by pauloricardomg** [fake-news-detector/extension#21]
* Screenshot
![loading](https://user-images.githubusercontent.com/259876/38162830-ec24bc78-34be-11e8-9b9a-7b7889f968bc.png)

* Environment details:
Firefox 59.0.2 (64-bit)
Ubuntu 16.04.2 LTS

Is this a server or client side problem? Let me know if there's additional troubleshooting info I can provide.

**Comment by rogeriochaves** [comment]
might be both hahaha, because on the latest commits I was doing some changes on the API and how the client read it, and unfortunatelly I made a breaking change without considering older versions

could you reinstall the extension (so you are sure to have the latest version) to see if it still happens?

**Comment by rogeriochaves** [comment]
wow, this http://odiarionacional.org is a very fake news website, maybe we should add it to the hardcoded list? (verified as fake or extremely biased) https://github.com/fake-news-detector/api/blob/master/src/data/verified_domains.rs

**Comment by pauloricardomg** [comment]
> could you reinstall the extension (so you are sure to have the latest version) to see if it still happens?

it's working now, thanks for the fix! will close this.

> wow, this http://odiarionacional.org is a very fake news website, maybe we should add it to the hardcoded list? (verified as fake or extremely biased)

It definitely looks like a dubious source, but I think going down the route of hard-coding sites as untrustable is dangerous, since it can be pretty hard to draw the line between what is opinion article and fake news, and legitimate news published by unstrutable sources. This occurs on the other direction too, since sites tagged as "legitimate" could also publish biased articles, so while articles published by these sites are likely trustable it's not a guarantee.

One example of a legitimate article published by this source is: http://odiarionacional.org/2018/03/29/jornal-aponta-que-stf-gasta-r-831-por-mes-com-85-segurancas-privados/

While the source is known to publish dubious news, this particular news is not fake in itself, so IMO the tool should not classify this particular article as fake news. Cases like the one above could be used by manipulators and uncredible sources to undermine the tool credibility.

For this particular problem, instead of blacklisting the whole website, IMO the tool should display a warning stating that "the article may be true, but this site is known to have extremely biased articles or fake news" -> and a pointer to dubious articles of this website (and why they tagged as such) so the user itself can decide whether to trust or not the source.

This problem is pretty hard, and mixing fake and non fake articles is exactly one of the tactics used by fake news propagators to make it hard to detect them. 

What do you think? Can you think of an easier solution to this problem? Do you think this is in the scope of this tool at this stage? Should we open another ticket to discuss this problem?

**Comment by pauloricardomg** [comment]
Created https://github.com/fake-news-detector/api/issues/30 to help solve the problem above and classify articles in good (following guidelines)/bad (not following guidelines), and sources as potentially trustworthy (if most of their articles follow the guidelines of good articles), or potentially untrustworthy (if the majority of their articles do not follow the "good-article" guidelines).
